disabled_rules: # Quy tắc bị loại trừ
  - colon
  - comma
  - identifier_name
  - control_statement
  - type_name
  - cyclomatic_complexity
  - function_body_length
  
opt_in_rules: # Các quy tắc bị tắt được bật
  - empty_count
  
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

excluded: # Các đường dẫn bỏ qua không thực thi trong khi chạy. Được ưu tiên hơn so với included`.
  - Carthage
  - Pods
  
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
  
line_length:
  warning: 200
  error: 250
  
file_length:
  warning: 500
  error: 800

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)


