disabled_rules:
    - line_length
    - type_name
    - file_length
    - identifier_name
    - type_body_length
    - function_body_length
    - no_fallthrough_only
    - todo
force_cast: warning
excluded:
    - Tests
cyclomatic_complexity:
    ignores_case_statements: true